{
 "title": "Text Summarizer Dashboard",
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Real Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rouge Score Over Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "summarizer",
     "rawSql": "SELECT prediction_ts AS \"time\", score_rouge1 AS \"rouge1\", score_rouge2 AS \"rouge2\", score_rougeL FROM summarizer.summarize_log ORDER BY prediction_ts DESC "
    }
   ]
  },
  {
   "title": "Query Channel Analysis",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  unix_timestamp(date_format(prediction_ts, \"%Y-%m-%d %H:00:00\")) AS \"time\", \n  model_source, \n  COUNT(prediction_id) as \"Channel - \"\nFROM \n  summarizer.summarize_log \nGROUP BY \n  unix_timestamp(date_format(prediction_ts, \"%Y-%m-%d %H:00:00\")), \n  model_source\nORDER BY\n  unix_timestamp(date_format(prediction_ts, \"%Y-%m-%d %H:00:00\"))"
    }
   ]
  },
  { "title": "Compress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Avg Document Length (char)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  unix_timestamp(date_format(prediction_ts, \"%Y-%m-%d %H:00:00\")) AS \"time\", \n  AVG(length(document)) as len_doc\nFROM \n  summarizer.summarize_log \nGROUP BY \n  unix_timestamp(date_format(prediction_ts, \"%Y-%m-%d %H:00:00\"))"
    }
   ]
  },
  {
   "title": "Avg Summary Length (char)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  unix_timestamp(date_format(prediction_ts, \"%Y-%m-%d %H:00:00\")) AS \"time\", \n  AVG(length(summary)) as model,\n  AVG(length(reference_summary)) as ref\nFROM \n  summarizer.summarize_log \nGROUP BY \n  unix_timestamp(date_format(prediction_ts, \"%Y-%m-%d %H:00:00\"))"
    }
   ]
  },
  {
   "title": "Compress Ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT \n  unix_timestamp(date_format(prediction_ts, \"%Y-%m-%d %H:00:00\")) AS \"time\", \n  SUM(length(summary)) / SUM(length(document)) as model,\n  SUM(length(reference_summary)) / SUM(length(document)) as ref\nFROM \n  summarizer.summarize_log \nGROUP BY \n  unix_timestamp(date_format(prediction_ts, \"%Y-%m-%d %H:00:00\"))"
    }
   ]
  },
  { "title": "Other Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Rouge Score Distribution",
   "type": "histogram",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "summarizer",
     "rawSql": "SELECT prediction_ts, score_rouge1, score_rouge2, score_rougeL FROM summarizer.summarize_log ORDER BY prediction_ts DESC LIMIT 500 "
    }
   ]
  },
  {
   "title": "Blue Score Distribution",
   "type": "histogram",
   "gridPos": { "h": 14, "w": 6, "x": 7, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "summarizer",
     "rawSql": "SELECT prediction_ts, score_blue FROM summarizer.summarize_log ORDER BY prediction_ts DESC LIMIT 500 "
    }
   ]
  },
  {
   "title": "Avg P100 Rouge1 Score",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 13, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "summarizer",
     "rawSql": "SELECT AVG(score_rouge1) FROM summarizer.summarize_log ORDER BY prediction_ts DESC LIMIT 100 "
    }
   ]
  },
  {
   "title": "Avg P100 RougeL Score",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "summarizer",
     "rawSql": "SELECT AVG(score_rougeL) FROM summarizer.summarize_log ORDER BY prediction_ts DESC LIMIT 100 "
    }
   ]
  },
  {
   "title": "Channel Split",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 5, "x": 19, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "summarizer",
     "rawSql": "SELECT model_source, COUNT(prediction_id) FROM summarizer.summarize_log GROUP BY model_source ORDER BY COUNT(prediction_id) DESC "
    }
   ]
  },
  {
   "title": "Avg P100 Rouge2 Score",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 13, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "summarizer",
     "rawSql": "SELECT AVG(score_rouge2) FROM summarizer.summarize_log ORDER BY prediction_ts DESC LIMIT 100 "
    }
   ]
  },
  {
   "title": "Avg P100 Blue Score",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "summarizer",
     "rawSql": "SELECT AVG(score_blue) FROM summarizer.summarize_log ORDER BY prediction_ts DESC LIMIT 100 "
    }
   ]
  }
 ]
}