name: build text summarizer model with mlflow
on:
  push: # will trigger workflow when push event
    paths:
      - 'deploy-mlflow/**' # will trigger when push to this path


jobs: # define two jobs, CI and CD
  # job1 - CI
  model-build:
    runs-on: ubuntu-latest
    steps:
      - name: Dockerhub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - uses: actions/checkout@v3
      
      - name: list files
        run: ls -l

      - name: read model version tag
        id: ver_tag
        uses: jbutcher5/read-yaml@main  # read yaml prebuilt action
        with:
          file: './deploy-mlflow/meta.yaml'
          key-path: '["model", "version-tag"]'

      - name: read dockerhub model name
        id: model_nm
        uses: jbutcher5/read-yaml@main  # read yaml prebuilt action
        with:
          file: './deploy-mlflow/meta.yaml'
          key-path: '["model", "docker-image-name"]'

      - name: Build and push image
        working-directory: deploy-mlflow
        run: |
          model_hub_nm = ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.model_nm.outputs.data }}
          docker build -t ${model_hub_nm}:${{ steps.ver_tag.outputs.data }} .
          docker tag ${model_hub_nm}:${{ steps.ver_tag.outputs.data }} ${model_hub_nm}:latest

          docker push ${model_hub_nm}:${{ steps.ver_tag.outputs.data }}
          docker push -f ${model_hub_nm}:latest
      