name: build text summarizer model with mlflow
on:
  push: # will trigger workflow when push event
    paths:
      - 'deploy-mlflow/**' # will trigger when push to this path

env:
  AWS_REGION: ca-central-1

jobs: # define two jobs, CI and CD
  # job1 - CI
  model-build:
    runs-on: ubuntu-latest
    steps:
      - name: Dockerhub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - uses: actions/checkout@v2
      
      - name: list files
        run: ls -l

      - name: read model version tag
        id: yaml_data
        uses: pietrobolcato/action-read-yaml@1.0.0  # read yaml prebuilt action
        with:
          config: './deploy-mlflow/meta.yaml'
      
      - name: Build image
        run: |
          npm install js-yaml
          echo ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.yaml_data.outputs['model.docker-image-name'] }}:${{ steps.yaml_data.outputs['model.version-tag'] }}
      