name: build text summarizer model with mlflow
on:
  push: # will trigger workflow when push event
    paths:
      - 'deploy-mlflow/**' # will trigger when push to this path

env:
  AWS_REGION: ca-central-1

jobs: # define two jobs, CI and CD
  # job1 - CI
  model-build:
    runs-on: ubuntu-latest
    steps:
      - name: Dockerhub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - uses: actions/checkout@v3
      
      - name: list files
        run: ls -l

      - name: read model version tag
        id: json_data
        uses: juliangruber/read-file-action@v1  # read yaml prebuilt action
        with:
          path: './deploy-mlflow/meta.json'
      
      - name: Build image
        run: |
          echo "${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.json_data.outputs.model }}"
      